# fly.toml app configuration file generated for chula-attendance-bot on 2026-02-23T18:03:49+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chula-attendance-bot'
primary_region = 'sin'

[build]
  dockerfile = 'Dockerfile'

[env]
  PYTHONUNBUFFERED = '1'

[[vm]]
  size = 'shared-cpu-1x'
  memory = 1024
